#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Introduction to DataCamp Projects" # Instructor fills out
description    : > # Instructor fills out
  If you have never done a DataCamp project, this is the place to start!  
long_description: | # Instructor fills out
  This is an introduction to DataCamp projects. DataCamp projects allow you to apply 
  the skills you have learned in DataCamp courses. In each project, you will carry out 
  an end-to-end analysis on real-world tasks using real-world tools and workflows.
  
  In doing so, you will learn how to work with Jupyter notebooks: an open-source web 
  application that is great for interactive data analysis.
  
individual_description: In this gentle introduction to DataCamp projects, we will walk you through the 
  project interface!
group_key: introduction-to-projects
time_needed: "30 minutes" # "30/45/60 minutes". # DataCamp fills out
is_guided: True

#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 1 # 1 == R, 2 == python, 3 == sql # Automatically set
# IDs for courses that are prerequisites
#  see https://mb.datacamp.com/question/126 for IDs
prerequisites: # DataCamp fills out
  - 58 # Introduction to R
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard # DataCamp fills outs
# IDs for the topics the project covers
# See here for topic IDs: http://bit.ly/project-topic-ids
topics: # DataCamp fills out
  - 4
  - 12

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : r # One of r, python or sql
# The name of the docker image used to run the course
from           : 'r-notebooks-prod:v2.4.0'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.
